"""Research report generation tool."""

from __future__ import annotations

import asyncio
import json
import os
import tarfile
import tempfile
from datetime import datetime

from agents.tool import function_tool


REPORT_TEMPLATE = """# Malware Research Report

**Sample SHA256:** {sample_sha256}
**Analysis Date:** {analysis_date}
**Analyst:** Kael Autonomous Agent

---

## Executive Summary

{executive_summary}

---

## File Triage

{file_triage}

---

## Static Analysis

### Strings & IOCs
{strings_analysis}

### YARA Matches
{yara_matches}

### Disassembly Highlights (Radare2)
{radare2_analysis}

---

## Dynamic Analysis

### Sandbox Execution
{sandbox_execution}

### Filesystem Changes
{filesystem_changes}

### Network Activity
{network_activity}

---

## Behavioral Analysis

### Syscalls & API Usage
{syscalls}

### C2 Beaconing
{c2_beaconing}

### Protocol Analysis
{protocol_analysis}

---

## Unpacking & Payloads

{unpacking}

---

## Memory Forensics

{memory_forensics}

---

## MITRE ATT&CK Mapping

{mitre_attack}

---

## Indicators of Compromise (IOCs)

### Network IOCs
{network_iocs}

### File IOCs
{file_iocs}

---

## Recommendations

{recommendations}

---

## Artifacts

All analysis artifacts have been packaged in:
`{tarball_path}`

**Contents:**
- Original sample
- Strace/ltrace logs
- PCAP file
- Memory dumps
- Unpacked payloads
- JSON analysis results

---

**Report generated by Kael v1.0 - Autonomous Malware Reverse Engineering**
"""


def format_file_triage(data: dict) -> str:
    """Format file triage section."""
    if not data or not data.get("success"):
        return "No file triage data available."

    output = []
    output.append(f"**File Type:** {data.get('file_type', 'unknown')}")
    output.append(f"**Size:** {data.get('file_size', 0)} bytes")

    if "hashes" in data:
        hashes = data["hashes"]
        output.append("\n**Hashes:**")
        output.append(f"- MD5: `{hashes.get('md5', 'N/A')}`")
        output.append(f"- SHA1: `{hashes.get('sha1', 'N/A')}`")
        output.append(f"- SHA256: `{hashes.get('sha256', 'N/A')}`")
        if "ssdeep" in hashes:
            output.append(f"- ssdeep: `{hashes.get('ssdeep', 'N/A')}`")

    if "entropy" in data:
        output.append(f"\n**Entropy:** {data['entropy']:.2f}")

    if data.get("packer_detected"):
        output.append(f"\n**Packer Detected:** {data.get('packer_name', 'Yes')}")

    return "\n".join(output)


def format_yara_matches(data: dict) -> str:
    """Format YARA matches section."""
    if not data or not data.get("success"):
        return "No YARA matches."

    matches = data.get("matches", [])
    if not matches:
        return "No YARA rules matched."

    output = [f"**{len(matches)} rule(s) matched:**\n"]

    for match in matches[:10]:  # Limit to 10
        output.append(f"- **{match.get('rule_name', 'unknown')}**")
        if "meta" in match and "description" in match["meta"]:
            output.append(f"  - {match['meta']['description']}")
        if match.get("tags"):
            output.append(f"  - Tags: {', '.join(match['tags'])}")

    return "\n".join(output)


def format_sandbox_execution(data: dict) -> str:
    """Format sandbox execution section."""
    if not data or not data.get("success"):
        return "No sandbox execution data available."

    exec_info = data.get("execution", {})
    output = []

    output.append(f"**Duration:** {exec_info.get('duration_sec', 0)} seconds")
    output.append(f"**Exit Status:** {exec_info.get('exit_status', 'unknown')}")

    if "filesystem_changes" in data:
        changes = data["filesystem_changes"]
        created = len(changes.get("created", []))
        modified = len(changes.get("modified", []))
        deleted = len(changes.get("deleted", []))

        if created or modified or deleted:
            output.append("\n**Filesystem Impact:**")
            output.append(f"- Created: {created} files")
            output.append(f"- Modified: {modified} files")
            output.append(f"- Deleted: {deleted} files")

    return "\n".join(output)


def format_c2_beaconing(data: dict) -> str:
    """Format C2 beaconing section."""
    if not data or not data.get("success"):
        return "No beaconing detected."

    beacons = data.get("beacons", [])
    if not beacons:
        return "No regular beaconing patterns detected."

    output = [f"**{len(beacons)} beacon pattern(s) detected:**\n"]

    for beacon in beacons[:5]:  # Top 5
        output.append(
            f"- **{beacon.get('destination', 'unknown')}** ({beacon.get('protocol', 'unknown')})"
        )
        stats = beacon.get("statistics", {})
        output.append(
            f"  - Interval: {stats.get('avg_interval_sec', 0):.2f}s (±{stats.get('jitter_sec', 0):.2f}s)"
        )
        output.append(f"  - Packets: {beacon.get('packet_count', 0)}")
        output.append(f"  - Confidence: {beacon.get('confidence', 'unknown')}")

    return "\n".join(output)


def create_tarball(sample_sha256: str, output_dir: str, artifacts_dir: str) -> str:
    """Create tarball of all artifacts."""
    tarball_path = os.path.join(output_dir, f"{sample_sha256}_artifacts.tar.gz")

    try:
        with tarfile.open(tarball_path, "w:gz") as tar:
            # Add artifacts directory if it exists
            if os.path.exists(artifacts_dir):
                tar.add(artifacts_dir, arcname=f"{sample_sha256}_artifacts")
    except Exception:
        tarball_path = "Failed to create tarball"

    return tarball_path


def generate_research_report_sync(
    sample_sha256: str,
    analysis_data: str,
    output_dir: str | None = None,
) -> str:
    """Synchronous report generation implementation."""

    # If no output_dir specified, use a temp directory or current working directory
    if output_dir is None:
        # Try to use current working directory + reports subdir
        output_dir = os.path.join(os.getcwd(), "kael-reports")
    elif output_dir.startswith("/workspace/"):
        # Container path specified - convert to host path
        # Use temp directory as fallback since we can't easily map workspace paths
        output_dir = os.path.join(tempfile.gettempdir(), "kael-reports")

    # Create output directory
    try:
        os.makedirs(output_dir, exist_ok=True)
    except PermissionError:
        # Fallback to temp directory
        output_dir = os.path.join(tempfile.gettempdir(), "kael-reports")
        os.makedirs(output_dir, exist_ok=True)

    try:
        # Parse analysis data
        try:
            data = json.loads(analysis_data)
        except Exception:
            return json.dumps({"success": False, "error": "Invalid analysis_data JSON"})

        # Extract individual analysis results
        file_triage = data.get("file_triage", {})
        strings_data = data.get("strings", {})
        yara_data = data.get("yara", {})
        radare2_data = data.get("radare2", {})
        sandbox_data = data.get("sandbox", {})
        c2_beacon_data = data.get("c2_beacon", {})
        protocol_data = data.get("protocol", {})
        unpack_data = data.get("unpack", {})
        memory_data = data.get("memory", {})

        # Generate executive summary
        executive_summary = f"""This sample ({sample_sha256[:16]}...) was analyzed using the Kael autonomous malware research platform.
Analysis included static triage, dynamic sandbox execution, network traffic capture, and behavioral analysis."""

        # Build report sections
        report_content = REPORT_TEMPLATE.format(
            sample_sha256=sample_sha256,
            analysis_date=datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC"),
            executive_summary=executive_summary,
            file_triage=format_file_triage(file_triage),
            strings_analysis=f"Extracted {strings_data.get('total_strings', 0)} strings"
            if strings_data
            else "N/A",
            yara_matches=format_yara_matches(yara_data),
            radare2_analysis=f"Identified {radare2_data.get('total_functions', 0)} functions"
            if radare2_data
            else "N/A",
            sandbox_execution=format_sandbox_execution(sandbox_data),
            filesystem_changes=f"{len(sandbox_data.get('filesystem_changes', {}).get('created', []))} files created"
            if sandbox_data
            else "N/A",
            network_activity="Captured in PCAP"
            if sandbox_data and sandbox_data.get("network")
            else "No network activity",
            syscalls=f"{len(sandbox_data.get('syscalls', {}).get('summary', {}))} unique syscalls"
            if sandbox_data
            else "N/A",
            c2_beaconing=format_c2_beaconing(c2_beacon_data),
            protocol_analysis=f"{protocol_data.get('total_packets', 0)} packets analyzed"
            if protocol_data
            else "N/A",
            unpacking=f"{unpack_data.get('total_unpacked', 0)} payloads extracted"
            if unpack_data
            else "No unpacking performed",
            memory_forensics=f"{len(memory_data.get('dumps', []))} memory dumps captured"
            if memory_data
            else "N/A",
            mitre_attack="TBD - Automated MITRE mapping not yet implemented",
            network_iocs="See protocol analysis section",
            file_iocs="See file triage section",
            recommendations="Follow-up with manual analysis for complex evasion techniques",
            tarball_path=f"{sample_sha256}_artifacts.tar.gz",
        )

        # Write markdown report
        report_path = os.path.join(output_dir, f"{sample_sha256}_report.md")
        with open(report_path, "w") as f:
            f.write(report_content)

        # Write JSON report
        json_path = os.path.join(output_dir, f"{sample_sha256}_report.json")
        with open(json_path, "w") as f:
            json.dump(data, f, indent=2)

        # Create tarball of artifacts (if they exist)
        artifacts_dir = f"/workspace/.re-runs/{sample_sha256}"
        tarball_path = None

        # Only try to create tarball if artifacts directory exists on host
        # (This won't work with /workspace paths from host, but we try anyway)
        if os.path.exists(artifacts_dir):
            tarball_path = create_tarball(sample_sha256, output_dir, artifacts_dir)
        else:
            # Artifacts might be in temp location or not exist yet
            tarball_path = "No artifacts directory found (sandbox run may not have completed)"

        result = {
            "success": True,
            "sample_sha256": sample_sha256,
            "report_markdown": report_path,
            "report_json": json_path,
            "artifacts_tarball": tarball_path,
            "output_dir": output_dir,
        }

        return json.dumps(result, indent=2)

    except Exception as e:
        return json.dumps({"success": False, "error": f"Report generation failed: {e!s}"})


@function_tool(timeout=60)
async def generate_research_report(
    sample_sha256: str,
    analysis_data: str,
    output_dir: str | None = None,
) -> str:
    """Generate comprehensive malware research report in markdown and JSON formats.

    Args:
        sample_sha256: SHA256 hash of the analyzed sample
        analysis_data: JSON string containing all analysis results
        output_dir: Directory to save reports (default: ./kael-reports/ in current directory)
                   If None, uses current working directory + 'kael-reports' subdirectory

    Returns:
        JSON string with paths to generated reports and artifacts tarball
    """
    return await asyncio.to_thread(
        generate_research_report_sync,
        sample_sha256,
        analysis_data,
        output_dir,
    )
